// Static map of ISO 3166-1 alpha-2 country codes to their primary currency and languages.
// This replaces the deprecated restcountries.com v3.1 API dependency.

export const COUNTRY_DATA = {
  AD: { currency: "EUR", languages: ["Catalan"] },
  AE: { currency: "AED", languages: ["Arabic"] },
  AF: { currency: "AFN", languages: ["Dari", "Pashto"] },
  AG: { currency: "XCD", languages: ["English"] },
  AL: { currency: "ALL", languages: ["Albanian"] },
  AM: { currency: "AMD", languages: ["Armenian"] },
  AO: { currency: "AOA", languages: ["Portuguese"] },
  AR: { currency: "ARS", languages: ["Spanish"] },
  AT: { currency: "EUR", languages: ["German"] },
  AU: { currency: "AUD", languages: ["English"] },
  AZ: { currency: "AZN", languages: ["Azerbaijani"] },
  BA: { currency: "BAM", languages: ["Bosnian", "Croatian", "Serbian"] },
  BB: { currency: "BBD", languages: ["English"] },
  BD: { currency: "BDT", languages: ["Bengali"] },
  BE: { currency: "EUR", languages: ["Dutch", "French", "German"] },
  BF: { currency: "XOF", languages: ["French"] },
  BG: { currency: "BGN", languages: ["Bulgarian"] },
  BH: { currency: "BHD", languages: ["Arabic"] },
  BI: { currency: "BIF", languages: ["French", "Kirundi"] },
  BJ: { currency: "XOF", languages: ["French"] },
  BN: { currency: "BND", languages: ["Malay"] },
  BO: { currency: "BOB", languages: ["Spanish", "Quechua", "Aymara"] },
  BR: { currency: "BRL", languages: ["Portuguese"] },
  BS: { currency: "BSD", languages: ["English"] },
  BT: { currency: "BTN", languages: ["Dzongkha"] },
  BW: { currency: "BWP", languages: ["English", "Tswana"] },
  BY: { currency: "BYN", languages: ["Belarusian", "Russian"] },
  BZ: { currency: "BZD", languages: ["English"] },
  CA: { currency: "CAD", languages: ["English", "French"] },
  CD: { currency: "CDF", languages: ["French"] },
  CF: { currency: "XAF", languages: ["French", "Sango"] },
  CG: { currency: "XAF", languages: ["French"] },
  CH: { currency: "CHF", languages: ["German", "French", "Italian", "Romansh"] },
  CI: { currency: "XOF", languages: ["French"] },
  CL: { currency: "CLP", languages: ["Spanish"] },
  CM: { currency: "XAF", languages: ["French", "English"] },
  CN: { currency: "CNY", languages: ["Chinese"] },
  CO: { currency: "COP", languages: ["Spanish"] },
  CR: { currency: "CRC", languages: ["Spanish"] },
  CU: { currency: "CUP", languages: ["Spanish"] },
  CV: { currency: "CVE", languages: ["Portuguese"] },
  CY: { currency: "EUR", languages: ["Greek", "Turkish"] },
  CZ: { currency: "CZK", languages: ["Czech"] },
  DE: { currency: "EUR", languages: ["German"] },
  DJ: { currency: "DJF", languages: ["Arabic", "French"] },
  DK: { currency: "DKK", languages: ["Danish"] },
  DM: { currency: "XCD", languages: ["English"] },
  DO: { currency: "DOP", languages: ["Spanish"] },
  DZ: { currency: "DZD", languages: ["Arabic"] },
  EC: { currency: "USD", languages: ["Spanish"] },
  EE: { currency: "EUR", languages: ["Estonian"] },
  EG: { currency: "EGP", languages: ["Arabic"] },
  ER: { currency: "ERN", languages: ["Tigrinya", "Arabic", "English"] },
  ES: { currency: "EUR", languages: ["Spanish"] },
  ET: { currency: "ETB", languages: ["Amharic"] },
  FI: { currency: "EUR", languages: ["Finnish", "Swedish"] },
  FJ: { currency: "FJD", languages: ["English", "Fijian", "Hindi"] },
  FK: { currency: "FKP", languages: ["English"] },
  FR: { currency: "EUR", languages: ["French"] },
  GA: { currency: "XAF", languages: ["French"] },
  GB: { currency: "GBP", languages: ["English"] },
  GD: { currency: "XCD", languages: ["English"] },
  GE: { currency: "GEL", languages: ["Georgian"] },
  GH: { currency: "GHS", languages: ["English"] },
  GM: { currency: "GMD", languages: ["English"] },
  GN: { currency: "GNF", languages: ["French"] },
  GQ: { currency: "XAF", languages: ["Spanish", "French", "Portuguese"] },
  GR: { currency: "EUR", languages: ["Greek"] },
  GT: { currency: "GTQ", languages: ["Spanish"] },
  GW: { currency: "XOF", languages: ["Portuguese"] },
  GY: { currency: "GYD", languages: ["English"] },
  HN: { currency: "HNL", languages: ["Spanish"] },
  HR: { currency: "EUR", languages: ["Croatian"] },
  HT: { currency: "HTG", languages: ["French", "Haitian Creole"] },
  HU: { currency: "HUF", languages: ["Hungarian"] },
  ID: { currency: "IDR", languages: ["Indonesian"] },
  IE: { currency: "EUR", languages: ["English", "Irish"] },
  IL: { currency: "ILS", languages: ["Hebrew", "Arabic"] },
  IN: { currency: "INR", languages: ["Hindi", "English"] },
  IQ: { currency: "IQD", languages: ["Arabic", "Kurdish"] },
  IR: { currency: "IRR", languages: ["Persian"] },
  IS: { currency: "ISK", languages: ["Icelandic"] },
  IT: { currency: "EUR", languages: ["Italian"] },
  JM: { currency: "JMD", languages: ["English"] },
  JO: { currency: "JOD", languages: ["Arabic"] },
  JP: { currency: "JPY", languages: ["Japanese"] },
  KE: { currency: "KES", languages: ["Swahili", "English"] },
  KG: { currency: "KGS", languages: ["Kyrgyz", "Russian"] },
  KH: { currency: "KHR", languages: ["Khmer"] },
  KI: { currency: "AUD", languages: ["English", "Gilbertese"] },
  KM: { currency: "KMF", languages: ["Comorian", "Arabic", "French"] },
  KN: { currency: "XCD", languages: ["English"] },
  KP: { currency: "KPW", languages: ["Korean"] },
  KR: { currency: "KRW", languages: ["Korean"] },
  KW: { currency: "KWD", languages: ["Arabic"] },
  KZ: { currency: "KZT", languages: ["Kazakh", "Russian"] },
  LA: { currency: "LAK", languages: ["Lao"] },
  LB: { currency: "LBP", languages: ["Arabic"] },
  LC: { currency: "XCD", languages: ["English"] },
  LI: { currency: "CHF", languages: ["German"] },
  LK: { currency: "LKR", languages: ["Sinhala", "Tamil"] },
  LR: { currency: "LRD", languages: ["English"] },
  LS: { currency: "LSL", languages: ["Sesotho", "English"] },
  LT: { currency: "EUR", languages: ["Lithuanian"] },
  LU: { currency: "EUR", languages: ["Luxembourgish", "French", "German"] },
  LV: { currency: "EUR", languages: ["Latvian"] },
  LY: { currency: "LYD", languages: ["Arabic"] },
  MA: { currency: "MAD", languages: ["Arabic", "Berber"] },
  MC: { currency: "EUR", languages: ["French"] },
  MD: { currency: "MDL", languages: ["Romanian"] },
  ME: { currency: "EUR", languages: ["Montenegrin"] },
  MG: { currency: "MGA", languages: ["Malagasy", "French"] },
  MH: { currency: "USD", languages: ["Marshallese", "English"] },
  MK: { currency: "MKD", languages: ["Macedonian"] },
  ML: { currency: "XOF", languages: ["French"] },
  MM: { currency: "MMK", languages: ["Burmese"] },
  MN: { currency: "MNT", languages: ["Mongolian"] },
  MR: { currency: "MRU", languages: ["Arabic"] },
  MT: { currency: "EUR", languages: ["Maltese", "English"] },
  MU: { currency: "MUR", languages: ["English", "French"] },
  MV: { currency: "MVR", languages: ["Dhivehi"] },
  MW: { currency: "MWK", languages: ["English", "Chichewa"] },
  MX: { currency: "MXN", languages: ["Spanish"] },
  MY: { currency: "MYR", languages: ["Malay"] },
  MZ: { currency: "MZN", languages: ["Portuguese"] },
  NA: { currency: "NAD", languages: ["English", "Afrikaans"] },
  NE: { currency: "XOF", languages: ["French"] },
  NG: { currency: "NGN", languages: ["English"] },
  NI: { currency: "NIO", languages: ["Spanish"] },
  NL: { currency: "EUR", languages: ["Dutch"] },
  NO: { currency: "NOK", languages: ["Norwegian"] },
  NP: { currency: "NPR", languages: ["Nepali"] },
  NR: { currency: "AUD", languages: ["Nauruan", "English"] },
  NZ: { currency: "NZD", languages: ["English", "Māori"] },
  OM: { currency: "OMR", languages: ["Arabic"] },
  PA: { currency: "PAB", languages: ["Spanish"] },
  PE: { currency: "PEN", languages: ["Spanish", "Quechua", "Aymara"] },
  PG: { currency: "PGK", languages: ["English", "Tok Pisin", "Hiri Motu"] },
  PH: { currency: "PHP", languages: ["Filipino", "English"] },
  PK: { currency: "PKR", languages: ["Urdu", "English"] },
  PL: { currency: "PLN", languages: ["Polish"] },
  PT: { currency: "EUR", languages: ["Portuguese"] },
  PW: { currency: "USD", languages: ["Palauan", "English"] },
  PY: { currency: "PYG", languages: ["Spanish", "Guaraní"] },
  QA: { currency: "QAR", languages: ["Arabic"] },
  RO: { currency: "RON", languages: ["Romanian"] },
  RS: { currency: "RSD", languages: ["Serbian"] },
  RU: { currency: "RUB", languages: ["Russian"] },
  RW: { currency: "RWF", languages: ["Kinyarwanda", "French", "English"] },
  SA: { currency: "SAR", languages: ["Arabic"] },
  SB: { currency: "SBD", languages: ["English"] },
  SC: { currency: "SCR", languages: ["Seychellois Creole", "French", "English"] },
  SD: { currency: "SDG", languages: ["Arabic", "English"] },
  SE: { currency: "SEK", languages: ["Swedish"] },
  SG: { currency: "SGD", languages: ["English", "Malay", "Chinese", "Tamil"] },
  SI: { currency: "EUR", languages: ["Slovenian"] },
  SK: { currency: "EUR", languages: ["Slovak"] },
  SL: { currency: "SLL", languages: ["English"] },
  SM: { currency: "EUR", languages: ["Italian"] },
  SN: { currency: "XOF", languages: ["French"] },
  SO: { currency: "SOS", languages: ["Somali", "Arabic"] },
  SR: { currency: "SRD", languages: ["Dutch"] },
  SS: { currency: "SSP", languages: ["English"] },
  ST: { currency: "STN", languages: ["Portuguese"] },
  SV: { currency: "USD", languages: ["Spanish"] },
  SY: { currency: "SYP", languages: ["Arabic"] },
  SZ: { currency: "SZL", languages: ["Swati", "English"] },
  TD: { currency: "XAF", languages: ["Arabic", "French"] },
  TG: { currency: "XOF", languages: ["French"] },
  TH: { currency: "THB", languages: ["Thai"] },
  TJ: { currency: "TJS", languages: ["Tajik", "Russian"] },
  TL: { currency: "USD", languages: ["Tetum", "Portuguese"] },
  TM: { currency: "TMT", languages: ["Turkmen"] },
  TN: { currency: "TND", languages: ["Arabic"] },
  TO: { currency: "TOP", languages: ["Tongan", "English"] },
  TR: { currency: "TRY", languages: ["Turkish"] },
  TT: { currency: "TTD", languages: ["English"] },
  TV: { currency: "AUD", languages: ["Tuvaluan", "English"] },
  TZ: { currency: "TZS", languages: ["Swahili", "English"] },
  UA: { currency: "UAH", languages: ["Ukrainian"] },
  UG: { currency: "UGX", languages: ["English", "Swahili"] },
  US: { currency: "USD", languages: ["English"] },
  UY: { currency: "UYU", languages: ["Spanish"] },
  UZ: { currency: "UZS", languages: ["Uzbek"] },
  VA: { currency: "EUR", languages: ["Italian", "Latin"] },
  VC: { currency: "XCD", languages: ["English"] },
  VE: { currency: "VES", languages: ["Spanish"] },
  VN: { currency: "VND", languages: ["Vietnamese"] },
  VU: { currency: "VUV", languages: ["Bislama", "English", "French"] },
  WS: { currency: "WST", languages: ["Samoan", "English"] },
  YE: { currency: "YER", languages: ["Arabic"] },
  ZA: { currency: "ZAR", languages: ["Zulu", "Xhosa", "Afrikaans", "English"] },
  ZM: { currency: "ZMW", languages: ["English"] },
  ZW: { currency: "ZWL", languages: ["Shona", "Ndebele", "English"] },
};

/**
 * Returns the primary currency code for a given ISO 3166-1 alpha-2 country code.
 * @param {string} countryCode  e.g. "FR"
 * @returns {string|null}
 */
export function getCurrencyForCountry(countryCode) {
  return COUNTRY_DATA[countryCode?.toUpperCase()]?.currency ?? null;
}

/**
 * Returns the languages spoken in a country.
 * @param {string} countryCode  e.g. "FR"
 * @returns {string[]}
 */
export function getLanguagesForCountry(countryCode) {
  return COUNTRY_DATA[countryCode?.toUpperCase()]?.languages ?? [];
}
